# ============================================================
# MÉXICO
# ============================================================
MEXICO_FACIL = [
    ("¿Quién fue el líder de la Revolución Mexicana conocido como 'El Centauro del Norte'?", "pancho villa"),
    ("¿En qué año se independizó México de España?", "1821"),
    ("¿Cuál es la capital de México?", "ciudad de mexico"),
    ("¿Quién fue el primer presidente de México?", "guadalupe victoria"),
    ("¿Qué civilización construyó Chichén Itzá?", "maya"),
    ("¿En qué año inició la Revolución Mexicana?", "1910"),
    ("¿Quién fue el emperador de México durante la intervención francesa?", "maximiliano"),
    ("¿Quién nacionalizó el petróleo en 1938?", "lazaro cardenas"),
    ("¿Qué civilización construyó Teotihuacán?", "teotihuacana"),
    ("¿Quién fue 'El Benemérito de las Américas'?", "benito juarez"),
    ("¿En qué año se firmó el Tratado de Guadalupe Hidalgo?", "1848"),
    ("¿Qué presidente mexicano duró 45 minutos en el cargo?", "pedro lascurain"),
    ("¿Quién lideró la conquista de México?", "hernan cortes"),
    ("¿Cuál era el nombre azteca de la Ciudad de México?", "tenochtitlan"),
    ("¿En qué año México perdió Texas?", "1836"),
    ("¿Qué movimiento inició el cura Miguel Hidalgo?", "independencia"),
    ("¿Quién fue el último emperador azteca?", "cuauhtemoc"),
    ("¿Qué fecha se celebra el Grito de Independencia?", "15 de septiembre"),
    ("¿Quién escribió 'La Suave Patria'?", "ramon lopez velarde"),
    ("¿Qué batalla ganó México el 5 de mayo de 1862?", "puebla"),
]

MEXICO_NORMAL = [
    ("¿En qué año se fundó Tenochtitlán?", "1325"),
    ("¿Qué emperador azteca recibió a Hernán Cortés?", "moctezuma"),
    ("¿Quién fue el virrey que impulsó las reformas borbónicas?", "jose de galvez"),
    ("¿En qué año se proclamó el Plan de Ayutla?", "1854"),
    ("¿Quién lideró la Guerra de Reforma?", "benito juarez"),
    ("¿Qué tratado vendió La Mesilla a EE.UU. en 1853?", "gadsden"),
    ("¿Quién fue el primer gobernante de México independiente?", "agustin de iturbide"),
    ("¿En qué año se fundó el PRI?", "1929"),
    ("¿Quién fue el último virrey de Nueva España?", "juan odonoju"),
    ("¿Qué batalla selló la independencia de México?", "calderon"),
    ("¿Quién fue 'El Apóstol de la Independencia'?", "miguel hidalgo"),
    ("¿En qué año México reconoció la independencia de Texas?", "1845"),
    ("¿Quién fue el autor del Plan de San Luis?", "francisco i madero"),
    ("¿Qué emperador azteca fue sucesor de Moctezuma II?", "cuitlahuac"),
    ("¿En qué año se fundó el IPN?", "1936"),
    ("¿Quién fue 'El Padre de la Patria' en México?", "miguel hidalgo"),
    ("¿Qué movimiento cultural surgió tras la Revolución?", "muralismo"),
    ("¿Quién fue el primer presidente electo después de la Revolución?", "alvaro obregon"),
    ("¿Quién fue 'El Caudillo del Sur'?", "emiliano zapata"),
    ("¿Quién fue el emperador azteca que resistió a los españoles?", "cuauhtemoc"),
]

MEXICO_DIFICIL = [
    ("¿En qué año se celebró el Primer Congreso Constituyente?", "1822"),
    ("¿Quién fue el virrey que aplicó las Leyes Nuevas?", "antonio de mendoza"),
    ("¿Qué tratado firmó México con España en 1836?", "santa maria calatrava"),
    ("¿En qué año se fundó el Partido Liberal Mexicano?", "1906"),
    ("¿Quién fue el redactor del Acta de Independencia?", "manuel de mier y teran"),
    ("¿Qué batalla enfrentó a Santa Anna y Houston?", "san jacinto"),
    ("¿En qué año se firmó el Plan de Tuxtepec?", "1876"),
    ("¿Quién fue el ideólogo del movimiento zapatista?", "ricardo flores magon"),
    ("¿Qué constitución abolió la esclavitud en México?", "1857"),
    ("¿Quién fue el autor del Plan de Tacubaya?", "felix maria zuloaga"),
    ("¿En qué año se creó el Departamento de Trabajo?", "1911"),
    ("¿Quién fue el primer gobernador de la Nueva España?", "hernan cortes"),
    ("¿Qué virrey fundó la Real y Pontificia Universidad?", "luis de velasco"),
    ("¿En qué año se promulgó la Ley Juárez?", "1855"),
    ("¿Quién fue el último presidente del Porfiriato?", "porfirio diaz"),
    ("¿Qué tratado puso fin a la guerra de Reforma?", "calpulalpan"),
    ("¿Quién fue el autor del Plan de la Noria?", "porfirio diaz"),
    ("¿En qué año se fundó el Banco de México?", "1925"),
    ("¿Quién fue el primer obispo de México?", "juan de zumarraga"),
    ("¿Qué presidente mexicano creó el IMSS?", "manuel avila camacho"),
]

# ============================================================
# CUBA
# ============================================================
CUBA_FACIL = [
    ("¿Quién fue el líder de la Revolución Cubana en 1959?", "fidel castro"),
    ("¿Cuál es la capital de Cuba?", "la habana"),
    ("¿En qué año se independizó Cuba formalmente?", "1902"),
    ("¿Quién fue el héroe nacional cubano del siglo XIX?", "jose marti"),
    ("¿Cómo se llama la moneda de Cuba?", "peso cubano"),
    ("¿Qué poeta cubano escribió 'Versos Sencillos'?", "jose marti"),
    ("¿En qué año triunfó la Revolución Cubana?", "1959"),
    ("¿Quién fue el líder del asalto al Cuartel Moncada?", "fidel castro"),
    ("¿Cuál es el río más largo de Cuba?", "cauto"),
    ("¿Qué país tiene una base naval en Guantánamo?", "estados unidos"),
    ("¿Quién fue el primer presidente de Cuba independiente?", "tomas estrada palma"),
    ("¿Qué médico cubano descubrió el mosquito de la fiebre amarilla?", "carlos finlay"),
    ("¿En qué año se abolió la esclavitud en Cuba?", "1886"),
    ("¿Cómo se llama el himno nacional de Cuba?", "la bayamesa"),
    ("¿Quién escribió la letra del himno de Bayamo?", "perucho figueredo"),
    ("¿Qué cubano ganó el Premio Nobel de Literatura?", "alejo carpentier"),
    ("¿Cuál es el pico más alto de Cuba?", "pico turquino"),
    ("¿En qué año comenzó la Guerra de los Diez Años?", "1868"),
    ("¿Quién fue el líder de la Protesta de Baraguá?", "antonio maceo"),
    ("¿Qué cubano es conocido como 'El Titán de Bronce'?", "antonio maceo"),
]

CUBA_NORMAL = [
    ("¿En qué año se firmó el Pacto del Zanjón?", "1878"),
    ("¿Quién fundó el Partido Revolucionario Cubano?", "jose marti"),
    ("¿En qué año se hundió el Maine en La Habana?", "1898"),
    ("¿Quién fue el primer presidente de la República en Armas?", "carlos manuel de cespedes"),
    ("¿Qué enmienda permitió a EE.UU. intervenir en Cuba?", "enmienda platt"),
    ("¿En qué año se proclamó la Constitución de 1940?", "1940"),
    ("¿Quién fue el presidente cubano derrocado por Batista?", "carlos prio socarras"),
    ("¿Qué movimiento fundó Fidel Castro en 1953?", "26 de julio"),
    ("¿En qué año se produjo la Crisis de los Misiles?", "1962"),
    ("¿Qué comandante dirigió la columna invasora en 1958?", "camilo cienfuegos"),
    ("¿Quién fue el Che Guevara en Cuba?", "ernesto guevara"),
    ("¿En qué año se fundó el PCC?", "1965"),
    ("¿Qué ley aprobó Cuba en 1961 sobre educación?", "alfabetizacion"),
    ("¿Quién fue el presidente de Cuba entre 2008 y 2018?", "raul castro"),
    ("¿En qué año se restablecieron relaciones Cuba-EE.UU.?", "2015"),
    ("¿Qué tratado de 1903 cedió Guantánamo a EE.UU.?", "tratado cubano americano"),
    ("¿En qué año se fundó el Partido Comunista de Cuba?", "1925"),
    ("¿Quién fue el último gobernador español en Cuba?", "adolfo jimenez castellanos"),
    ("¿Qué cubano dirigió la Revolución de 1930?", "antonio guiteras"),
    ("¿En qué año se aprobó la nueva Constitución cubana?", "2019"),
]

CUBA_DIFICIL = [
    ("¿En qué año se fundó la Universidad de La Habana?", "1728"),
    ("¿Quién fue el primer obispo de Cuba?", "diego de salcedo"),
    ("¿Qué virrey de Nueva España ordenó la ocupación de Cuba?", "diego velazquez"),
    ("¿En qué año se trasladó la capital de Santiago a La Habana?", "1553"),
    ("¿Quién fue el cronista oficial de la conquista de Cuba?", "bartolome de las casas"),
    ("¿En qué año se creó la Capitanía General de Cuba?", "1777"),
    ("¿Quién fue el primer capitán general de Cuba?", "luis de las casas"),
    ("¿Qué tratado de 1763 devolvió Cuba a España?", "paris"),
    ("¿En qué año se fundó el Ateneo de La Habana?", "1877"),
    ("¿Quién fue el fundador del PRC en Tampa?", "jose marti"),
    ("¿En qué año se produjo la primera intervención de EE.UU.?", "1899"),
    ("¿Quién fue el primer gobernador militar de EE.UU. en Cuba?", "john brook"),
    ("¿Qué reforma agraria aprobó Cuba en 1959?", "primera ley de reforma agraria"),
    ("¿En qué año se creó el Ministerio de Industrias?", "1961"),
    ("¿Quién fue el primer ministro de Relaciones Exteriores tras 1959?", "raul roa"),
    ("¿En qué año Cuba firmó el Tratado de Tlatelolco?", "1967"),
    ("¿Quién fue el embajador cubano en la ONU durante la Crisis?", "mario garcia inchaustegui"),
    ("¿En qué año se celebró el Primer Congreso del PCC?", "1975"),
    ("¿Quién fue el primer presidente del Instituto Cubano del Libro?", "alejo carpentier"),
    ("¿En qué año Cuba adoptó el peso convertible?", "1994"),
]

# ============================================================
# EL SALVADOR
# ============================================================
EL_SALVADOR_FACIL = [
    ("¿Cuál es la capital de El Salvador?", "san salvador"),
    ("¿En qué año se independizó El Salvador de España?", "1821"),
    ("¿Quién fue el prócer salvadoreño que firmó el Acta?", "jose matias delgado"),
    ("¿Cómo se llama la moneda oficial de El Salvador?", "dolar"),
    ("¿En qué año se firmaron los Acuerdos de Paz?", "1992"),
    ("¿Quién fue el líder del FMLN durante la guerra civil?", "schafik handal"),
    ("¿Qué volcán es el más alto de El Salvador?", "santa ana"),
    ("¿Quién fue el 'Padre de la Patria' salvadoreño?", "jose matias delgado"),
    ("¿En qué año terminó la guerra civil salvadoreña?", "1992"),
    ("¿Cuál es el río más largo de El Salvador?", "lempa"),
    ("¿Qué arzobispo fue asesinado en 1980?", "oscar romero"),
    ("¿En qué año se fundó la República de El Salvador?", "1824"),
    ("¿Quién fue el primer presidente de El Salvador?", "juan lindo"),
    ("¿Qué idioma se habla en El Salvador?", "espanol"),
    ("¿Cuál es el platillo típico de El Salvador?", "pupusa"),
    ("¿Qué cultura precolombina habitó El Salvador?", "maya"),
    ("¿En qué año se abolió la esclavitud en El Salvador?", "1824"),
    ("¿Quién fue el héroe nacional del siglo XIX?", "gerardo barrios"),
    ("¿Cuál es el departamento donde está la capital?", "san salvador"),
    ("¿En qué año se adoptó el dólar como moneda?", "2001"),
]

EL_SALVADOR_NORMAL = [
    ("¿En qué año se fundó San Salvador?", "1525"),
    ("¿Quién conquistó El Salvador para España?", "pedro de alvarado"),
    ("¿En qué año se creó la Provincia de San Salvador?", "1821"),
    ("¿Quién fue el primer obispo de San Salvador?", "jorge viteri"),
    ("¿En qué año se anexó El Salvador a México?", "1821"),
    ("¿Qué tratado separó El Salvador de la Federación?", "tratado de paz"),
    ("¿Quién fue el presidente que impulsó la reforma agraria?", "jose napoleon duarte"),
    ("¿En qué año se fundó el Partido Comunista de El Salvador?", "1930"),
    ("¿Quién lideró la matanza de 1932?", "maximiliano hernandez martinez"),
    ("¿En qué año ocurrió la masacre de El Mozote?", "1981"),
    ("¿Qué comandante dirigió el FMLN en los 80?", "joaquin villalobos"),
    ("¿En qué año se firmó el Acuerdo de Chapultepec?", "1992"),
    ("¿Quién fue el primer presidente electo tras los Acuerdos?", "alfredo cristiani"),
    ("¿Qué obispo fue beatificado en 2015?", "oscar romero"),
    ("¿En qué año se canonizó a Óscar Romero?", "2018"),
    ("¿Quién fue el fundador de la Universidad de El Salvador?", "gerardo barrios"),
    ("¿En qué año se fundó la UES?", "1841"),
    ("¿Qué presidente salvadoreño creó el ISSS?", "oscar osorio"),
    ("¿Quién fue el último presidente del siglo XX?", "francisco flores"),
    ("¿En qué año se fundó el FMLN como partido?", "1992"),
]

EL_SALVADOR_DIFICIL = [
    ("¿En qué año se fundó la Alcaldía de San Salvador?", "1525"),
    ("¿Quién fue el primer alcalde de San Salvador?", "diego de alvarado"),
    ("¿En qué año se trasladó la capital de Suchitoto?", "1540"),
    ("¿Qué pirata atacó San Salvador en 1682?", "francisco lopez"),
    ("¿En qué año se creó la Intendencia de San Salvador?", "1786"),
    ("¿Quién fue el primer intendente de San Salvador?", "jose ortiz de la peña"),
    ("¿En qué año se proclamó la independencia de San Salvador?", "1821"),
    ("¿Quién firmó el Acta de Independencia de Centroamérica?", "jose matias delgado"),
    ("¿En qué año se creó el Estado de El Salvador?", "1824"),
    ("¿Quién fue el primer jefe de Estado de El Salvador?", "juan manuel rodriguez"),
    ("¿En qué año se disolvió la Federación Centroamericana?", "1841"),
    ("¿Quién fue el presidente que impulsó la educación?", "gerardo barrios"),
    ("¿En qué año se fundó el Banco Central de Reserva?", "1934"),
    ("¿Quién fue el presidente durante la guerra del fútbol?", "fidel sanchez hernandez"),
    ("¿En qué año ocurrió la guerra del fútbol?", "1969"),
    ("¿Quién fue el presidente depuesto por un golpe en 1979?", "carlos humberto romero"),
    ("¿En qué año se creó la Fuerza Armada de El Salvador?", "1841"),
    ("¿Qué comandante guerrillero murió en 1989?", "ana guadalupe martinez"),
    ("¿En qué año se desmovilizó el FMLN?", "1992"),
    ("¿Quién fue el primer presidente del FMLN en el gobierno?", "mauricio funes"),
]

# ============================================================
# ECUADOR
# ============================================================
ECUADOR_FACIL = [
    ("¿Cuál es la capital de Ecuador?", "quito"),
    ("¿En qué año se independizó Ecuador de España?", "1822"),
    ("¿Quién fue el prócer conocido como 'El Precursor'?", "eugenio espejo"),
    ("¿Cómo se llama la moneda oficial de Ecuador?", "dolar"),
    ("¿Qué país limita al norte con Ecuador?", "colombia"),
    ("¿Qué país limita al sur con Ecuador?", "peru"),
    ("¿Cuál es el volcán más alto de Ecuador?", "chimborazo"),
    ("¿En qué año se fundó la República de Ecuador?", "1830"),
    ("¿Quién fue el primer presidente de Ecuador?", "juan jose flores"),
    ("¿Qué islas pertenecen a Ecuador y son famosas por Darwin?", "galapagos"),
    ("¿Quién fue el libertador que ayudó a Ecuador?", "simon bolivar"),
    ("¿Qué mariscal venció en Pichincha?", "antonio jose de sucre"),
    ("¿En qué año se abolió la esclavitud en Ecuador?", "1851"),
    ("¿Quién abolió la esclavitud en Ecuador?", "jose maria urbina"),
    ("¿Cuál es el río más largo de Ecuador?", "napo"),
    ("¿Qué cultura precolombina habitó Ecuador?", "inca"),
    ("¿En qué año se creó la Gran Colombia?", "1819"),
    ("¿Quién fue el último presidente de la Gran Colombia?", "simon bolivar"),
    ("¿Cuál es el plato típico de Ecuador?", "encebollado"),
    ("¿En qué año se separó Ecuador de la Gran Colombia?", "1830"),
]

ECUADOR_NORMAL = [
    ("¿En qué año se fundó Quito?", "1534"),
    ("¿Quién conquistó Quito para España?", "sebastian de benalcazar"),
    ("¿En qué año se creó la Real Audiencia de Quito?", "1563"),
    ("¿Quién fue el primer presidente de la Audiencia?", "hernando de santillan"),
    ("¿En qué año se produjo el primer grito de Quito?", "1809"),
    ("¿Quién fue el líder de la Revolución de Quito de 1809?", "juan pio montufar"),
    ("¿En qué año se firmó la independencia de Guayaquil?", "1820"),
    ("¿Quién fue el prócer guayaquileño de 1820?", "jose joaquin de olmedo"),
    ("¿En qué año se fundó el Partido Liberal de Ecuador?", "1895"),
    ("¿Quién fue el líder de la Revolución Liberal?", "eloy alfaro"),
    ("¿En qué año se promulgó la Constitución de Ecuador?", "2008"),
    ("¿Quién fue el presidente durante la crisis de 1999?", "jamil mahuad"),
    ("¿En qué año se adoptó el dólar en Ecuador?", "2000"),
    ("¿Quién fue el presidente entre 2007 y 2017?", "rafael correa"),
    ("¿En qué año se fundó el Ecuador como república?", "1830"),
    ("¿Qué tratado definió los límites Ecuador-Perú?", "rio de janeiro"),
    ("¿En qué año ocurrió la guerra del Cenepa?", "1995"),
    ("¿Quién fue el presidente durante la guerra del Cenepa?", "sixto duran ballen"),
    ("¿En qué año se firmó la paz entre Ecuador y Perú?", "1998"),
    ("¿Qué presidente ecuatoriano fue derrocado en 2005?", "lucio gutierrez"),
]

ECUADOR_DIFICIL = [
    ("¿En qué año llegó Francisco Pizarro a Ecuador?", "1532"),
    ("¿Quién fue el último inca de Quito?", "atahualpa"),
    ("¿En qué año se fundó la ciudad de Guayaquil?", "1538"),
    ("¿Quién fue el fundador de Guayaquil?", "francisco de orellana"),
    ("¿En qué año se creó la Presidencia de Quito?", "1563"),
    ("¿Quién fue el primer presidente de la Audiencia?", "hernando de santillan"),
    ("¿Qué terremoto destruyó Quito en 1797?", "terremoto de riobamba"),
    ("¿En qué año se creó el Colegio San Fernando?", "1800"),
    ("¿Quién fue el primer obispo de Quito?", "garci diaz arias"),
    ("¿En qué año se firmó el Tratado de Guayaquil?", "1829"),
    ("¿Quién fue el primer vicepresidente de Ecuador?", "jose joaquin de olmedo"),
    ("¿En qué año se creó el Banco Central del Ecuador?", "1927"),
    ("¿Quién impulsó la reforma agraria en Ecuador?", "rodriguez lara"),
    ("¿En qué año se dio el auge cacaotero?", "1880"),
    ("¿Quién fue el presidente asesinado en 1875?", "gabriel garcia moreno"),
    ("¿En qué año fue asesinado García Moreno?", "1875"),
    ("¿Quién fue el líder de la revolución alfarista?", "eloy alfaro"),
    ("¿En qué año fue asesinado Eloy Alfaro?", "1912"),
    ("¿Qué presidente fundó el Seguro Social?", "jose maria velasco ibarra"),
    ("¿En qué año se aprobó el voto femenino en Ecuador?", "1929"),
]

# ============================================================
# ARGENTINA
# ============================================================
ARGENTINA_FACIL = [
    ("¿Cuál es la capital de Argentina?", "buenos aires"),
    ("¿En qué año se independizó Argentina de España?", "1816"),
    ("¿Quién fue el libertador argentino más famoso?", "jose de san martin"),
    ("¿Qué día se celebra el Día de la Independencia Argentina?", "9 de julio"),
    ("¿Quién fue el primer presidente de Argentina?", "bernardino rivadavia"),
    ("¿En qué año se produjo la Revolución de Mayo?", "1810"),
    ("¿Cómo se llama la moneda oficial de Argentina?", "peso argentino"),
    ("¿Quién escribió el himno nacional argentino?", "vicente lopez y planes"),
    ("¿Qué prócer argentino creó la bandera?", "manuel belgrano"),
    ("¿En qué año se declaró la independencia en Tucumán?", "1816"),
    ("¿Cuál es el río más ancho de Argentina?", "rio de la plata"),
    ("¿Qué país limita al oeste con Argentina?", "chile"),
    ("¿Quién fue el presidente que impulsó la educación pública?", "domingo faustino sarmiento"),
    ("¿En qué año se aprobó la Ley Sáenz Peña?", "1912"),
    ("¿Quién fue Eva Perón?", "maria eva duarte de peron"),
    ("¿Qué deporte es el más popular en Argentina?", "futbol"),
    ("¿En qué año ganó Argentina su primer mundial?", "1978"),
    ("¿Quién fue el presidente entre 1946 y 1955?", "juan domingo peron"),
    ("¿Cuál es el pico más alto de Argentina?", "aconcagua"),
    ("¿En qué año se recuperaron las Islas Malvinas?", "1982"),
]

ARGENTINA_NORMAL = [
    ("¿En qué año se fundó Buenos Aires?", "1536"),
    ("¿Quién fundó Buenos Aires por primera vez?", "pedro de mendoza"),
    ("¿En qué año se creó el Virreinato del Río de la Plata?", "1776"),
    ("¿Quién fue el primer virrey del Río de la Plata?", "pedro de ceballos"),
    ("¿En qué año se produjo la segunda fundación de Buenos Aires?", "1580"),
    ("¿Quién fue el fundador definitivo de Buenos Aires?", "juan de garay"),
    ("¿Qué virrey fue depuesto en la Revolución de Mayo?", "baltasar hidalgo de cisneros"),
    ("¿Quién presidió la Primera Junta de Gobierno?", "cornelio saavedra"),
    ("¿En qué año se creó la Bandera Argentina?", "1812"),
    ("¿Dónde fue izada por primera vez la bandera argentina?", "rosario"),
    ("¿En qué año se sancionó la Constitución Nacional?", "1853"),
    ("¿Quién fue el autor del libro 'Facundo'?", "domingo faustino sarmiento"),
    ("¿En qué año se federalizó Buenos Aires?", "1880"),
    ("¿Quién fue el primer presidente de la Nación Argentina?", "julio argentino roca"),
    ("¿En qué año se aprobó el voto femenino en Argentina?", "1947"),
    ("¿Quién impulsó el voto femenino en Argentina?", "juan domingo peron"),
    ("¿En qué año se produjo el golpe contra Yrigoyen?", "1930"),
    ("¿Quién fue el líder de la Revolución Libertadora?", "eduardo lonardi"),
    ("¿En qué año volvió Perón a Argentina?", "1973"),
    ("¿En qué año se produjo el golpe militar?", "1976"),
]

ARGENTINA_DIFICIL = [
    ("¿En qué año se produjo la primera fundación de Buenos Aires?", "1536"),
    ("¿Qué gobernador español ordenó fundar Buenos Aires?", "pedro de mendoza"),
    ("¿En qué año se estableció la Gobernación del Río de la Plata?", "1617"),
    ("¿Quién fue el primer gobernador del Río de la Plata?", "hernandarias"),
    ("¿En qué año se creó la Real Audiencia de Buenos Aires?", "1661"),
    ("¿Qué tratado de 1750 definió límites entre España y Portugal?", "tratado de madrid"),
    ("¿En qué año se estableció el Consulado de Buenos Aires?", "1794"),
    ("¿Quién fue el primer secretario del Consulado?", "manuel belgrano"),
    ("¿En qué año se produjo la invasión inglesa a Buenos Aires?", "1806"),
    ("¿Quién lideró la defensa de Buenos Aires en 1806?", "santiago de liniers"),
    ("¿En qué año se produjo la segunda invasión inglesa?", "1807"),
    ("¿Quién fue el primer presidente de la Junta Grande?", "cornelio saavedra"),
    ("¿En qué año se disolvió la Junta Grande?", "1811"),
    ("¿Quién fue el autor del Plan de Mayo?", "mariano moreno"),
    ("¿En qué año se creó la Asamblea del Año XIII?", "1813"),
    ("¿Quién fue el director supremo en 1816?", "juan martin de pueyrredon"),
    ("¿En qué año se produjo la batalla de Cepeda?", "1820"),
    ("¿Quién fue el primer gobernador de Buenos Aires tras 1820?", "martin rodriguez"),
    ("¿En qué año se firmó el Pacto Federal?", "1831"),
    ("¿Quién fue el gobernador durante la Confederación?", "juan manuel de rosas"),
]

# ============================================================
# COLOMBIA
# ============================================================
COLOMBIA_FACIL = [
    ("¿Cuál es la capital de Colombia?", "bogota"),
    ("¿En qué año se independizó Colombia de España?", "1810"),
    ("¿Quién fue el libertador de Colombia?", "simon bolivar"),
    ("¿Cómo se llama la moneda oficial de Colombia?", "peso colombiano"),
    ("¿Qué país limita al este con Colombia?", "venezuela"),
    ("¿Cuál es el río más importante de Colombia?", "magdalena"),
    ("¿En qué año se firmó la independencia definitiva?", "1819"),
    ("¿Qué batalla selló la independencia de Colombia?", "boyaca"),
    ("¿Quién fue el prócer conocido como 'El Precursor'?", "antonio nariño"),
    ("¿Qué ciudad es conocida como la 'Atenas Suramericana'?", "bogota"),
    ("¿En qué año se creó la Gran Colombia?", "1819"),
    ("¿Quién fue el primer presidente de Colombia?", "simon bolivar"),
    ("¿Cuál es el plato típico de Colombia?", "bandeja paisa"),
    ("¿En qué año se abolió la esclavitud en Colombia?", "1851"),
    ("¿Quién abolió la esclavitud en Colombia?", "jose hilario lopez"),
    ("¿Qué país se separó de Colombia en 1903?", "panama"),
    ("¿En qué año se promulgó la Constitución actual?", "1991"),
    ("¿Quién fue el líder de la independencia de Cartagena?", "pedro romero"),
    ("¿En qué año se fundó Bogotá?", "1538"),
    ("¿Quién fundó Bogotá?", "gonzalo jimenez de quesada"),
]

COLOMBIA_NORMAL = [
    ("¿En qué año se creó el Virreinato de Nueva Granada?", "1717"),
    ("¿Quién fue el primer virrey de Nueva Granada?", "jorge de villalonga"),
    ("¿En qué año se produjo el grito de independencia?", "1810"),
    ("¿Quién fue el líder del 20 de julio?", "jose gonzalez llorente"),
    ("¿En qué año se creó el Estado de Cundinamarca?", "1811"),
    ("¿Quién fue el presidente de Cundinamarca?", "jorge tadeo lozano"),
    ("¿En qué año se produjo la reconquista española?", "1815"),
    ("¿Quién lideró la reconquista en Nueva Granada?", "pablo morillo"),
    ("¿En qué año se produjo el fusilamiento de la Pola?", "1817"),
    ("¿Quién fue 'La Pola'?", "policarpa salavarrieta"),
    ("¿En qué año se creó la Gran Colombia?", "1819"),
    ("¿Quién fue el vicepresidente de la Gran Colombia?", "francisco de paula santander"),
    ("¿En qué año se disolvió la Gran Colombia?", "1831"),
    ("¿Quién fue el primer presidente de la Nueva Granada?", "francisco de paula santander"),
    ("¿En qué año se promulgó la Constitución de Rionegro?", "1863"),
    ("¿En qué año se produjo la guerra de los Mil Días?", "1899"),
    ("¿En qué año se separó Panamá de Colombia?", "1903"),
    ("¿En qué año se produjo el Bogotazo?", "1948"),
    ("¿Quién fue asesinado en el Bogotazo?", "jorge eliecer gaitan"),
    ("¿En qué año se firmó el acuerdo de paz con las FARC?", "2016"),
]

COLOMBIA_DIFICIL = [
    ("¿En qué año llegó Jiménez de Quesada a Bogotá?", "1538"),
    ("¿Qué cultura precolombina habitó la sabana de Bogotá?", "muisca"),
    ("¿En qué año se creó la Real Audiencia de Santafé?", "1549"),
    ("¿Quién fue el primer presidente de la Audiencia?", "andres diaz venero de leiva"),
    ("¿En qué año se estableció el Nuevo Reino de Granada?", "1550"),
    ("¿Quién fue el primer gobernador de Popayán?", "sebastian de benalcazar"),
    ("¿En qué año se creó la Capitanía General de Venezuela?", "1777"),
    ("¿En qué año se produjo la rebelión de los Comuneros?", "1781"),
    ("¿Quién fue el líder de los Comuneros del Socorro?", "jose antonio galan"),
    ("¿En qué año se tradujeron los Derechos del Hombre?", "1794"),
    ("¿Quién tradujo los Derechos del Hombre?", "antonio nariño"),
    ("¿En qué año fue encarcelado Nariño?", "1795"),
    ("¿En qué año se proclamó la independencia de Cartagena?", "1811"),
    ("¿Quién fue el primer presidente de las Provincias Unidas?", "camilo torres"),
    ("¿En qué año se proclamó la independencia de Antioquia?", "1813"),
    ("¿Quién fue el primer presidente de Antioquia?", "juan del corral"),
    ("¿En qué año se produjo la batalla de Cachirí?", "1816"),
    ("¿Quién fue el último virrey de Nueva Granada?", "juan de samano"),
    ("¿En qué año se fundó el Colegio del Rosario?", "1653"),
    ("¿En qué año se fundó la Universidad de Antioquia?", "1803"),
]

# ============================================================
# PERÚ
# ============================================================
PERU_FACIL = [
    ("¿Cuál es la capital de Perú?", "lima"),
    ("¿En qué año se independizó Perú de España?", "1821"),
    ("¿Quién fue el libertador de Perú?", "jose de san martin"),
    ("¿Cómo se llama la moneda oficial de Perú?", "sol"),
    ("¿Qué país limita al norte con Perú?", "ecuador"),
    ("¿Qué país limita al sur con Perú?", "chile"),
    ("¿Cuál es el río más largo de Perú?", "amazonas"),
    ("¿En qué año se selló la independencia de Perú?", "1824"),
    ("¿Qué batalla selló la independencia de Perú?", "ayacucho"),
    ("¿Quién fue el último inca de Perú?", "atahualpa"),
    ("¿Qué ciudad fue la capital del Imperio Inca?", "cusco"),
    ("¿Qué cultura construyó Machu Picchu?", "inca"),
    ("¿Quién conquistó el Imperio Inca?", "francisco pizarro"),
    ("¿Cuál es el plato típico de Perú?", "ceviche"),
    ("¿En qué año se creó el Virreinato del Perú?", "1542"),
    ("¿Quién fue el primer virrey del Perú?", "blasco nunez vela"),
    ("¿En qué año se fundó Lima?", "1535"),
    ("¿Quién fundó Lima?", "francisco pizarro"),
    ("¿En qué año se abolió la esclavitud en Perú?", "1854"),
    ("¿Quién abolió la esclavitud en Perú?", "ramon castilla"),
]

PERU_NORMAL = [
    ("¿En qué año se creó la Real Audiencia de Lima?", "1543"),
    ("¿Quién fue el primer presidente de la Audiencia?", "cristobal vaca de castro"),
    ("¿En qué año se produjo la rebelión de Túpac Amaru II?", "1780"),
    ("¿Quién fue Túpac Amaru II?", "jose gabriel condorcanqui"),
    ("¿En qué año se proclamó la independencia de Perú?", "1821"),
    ("¿Quién proclamó la independencia de Perú?", "jose de san martin"),
    ("¿En qué año se reunió el Primer Congreso Constituyente?", "1822"),
    ("¿Quién fue el primer presidente del Perú independiente?", "jose de la riva aguero"),
    ("¿En qué año se creó la Confederación Perú-Boliviana?", "1836"),
    ("¿Quién fue el protector de la Confederación?", "andres de santa cruz"),
    ("¿En qué año se disolvió la Confederación?", "1839"),
    ("¿En qué año se produjo la guerra del Pacífico?", "1879"),
    ("¿Quién fue el presidente durante la guerra del Pacífico?", "mariano ignacio prado"),
    ("¿En qué año se firmó el Tratado de Ancón?", "1883"),
    ("¿En qué año se produjo la guerra con Ecuador?", "1941"),
    ("¿Quién fue el presidente peruano en 1941?", "manuel prado ugarteche"),
    ("¿En qué año se firmó el Protocolo de Río de Janeiro?", "1942"),
    ("¿En qué año se nacionalizó el petróleo en Perú?", "1968"),
    ("¿Quién nacionalizó el petróleo en Perú?", "juan velasco alvarado"),
    ("¿En qué año se promulgó la Constitución actual?", "1993"),
]

PERU_DIFICIL = [
    ("¿En qué año llegó Francisco Pizarro a Perú?", "1532"),
    ("¿En qué año se fundó el Virreinato del Perú?", "1542"),
    ("¿Quién fue el primer virrey del Perú?", "blasco nunez vela"),
    ("¿En qué año se creó la Universidad de San Marcos?", "1551"),
    ("¿Quién fundó la Universidad de San Marcos?", "carlos v"),
    ("¿En qué año se produjo la rebelión de Manco Inca?", "1536"),
    ("¿Quién fue el último virrey del Perú?", "jose de la serna"),
    ("¿En qué año se produjo la batalla de Junín?", "1824"),
    ("¿Quién dirigió la batalla de Junín?", "simon bolivar"),
    ("¿En qué año se produjo la batalla de Ayacucho?", "1824"),
    ("¿Quién dirigió la batalla de Ayacucho?", "antonio jose de sucre"),
    ("¿En qué año se creó la Confederación Perú-Boliviana?", "1836"),
    ("¿En qué año se produjo la batalla de Yungay?", "1839"),
    ("¿Quién firmó el Tratado de Ancón por Perú?", "jose antonio de lavalle"),
    ("¿En qué año se creó el Banco Central de Reserva?", "1922"),
    ("¿En qué año se produjo el Oncenio de Leguía?", "1919"),
    ("¿Quién fue el presidente del Oncenio?", "augusto b leguia"),
    ("¿En qué año se fundó el APRA?", "1924"),
    ("¿Quién fundó el APRA?", "victor raul haya de la torre"),
    ("¿En qué año se produjo el golpe de Velasco?", "1968"),
]

# ============================================================
# CHILE
# ============================================================
CHILE_FACIL = [
    ("¿Cuál es la capital de Chile?", "santiago"),
    ("¿En qué año se independizó Chile de España?", "1818"),
    ("¿Quién fue el libertador de Chile?", "bernardo o'higgins"),
    ("¿Cómo se llama la moneda oficial de Chile?", "peso chileno"),
    ("¿Qué país limita al este con Chile?", "argentina"),
    ("¿Qué país limita al norte con Chile?", "peru"),
    ("¿Cuál es el desierto más árido del mundo?", "atacama"),
    ("¿Qué océano baña las costas de Chile?", "pacifico"),
    ("¿En qué año se proclamó la independencia de Chile?", "1818"),
    ("¿Qué batalla selló la independencia de Chile?", "maipu"),
    ("¿Quién fue 'El Padre de la Patria' chileno?", "bernardo o'higgins"),
    ("¿Cuál es el plato típico de Chile?", "empanada"),
    ("¿Qué poeta chileno ganó el Premio Nobel?", "pablo neruda"),
    ("¿En qué año ganó Chile su primer mundial?", "1962"),
    ("¿Qué isla pertenece a Chile y tiene moáis?", "pascua"),
    ("¿En qué año se abolió la esclavitud en Chile?", "1823"),
    ("¿Quién fue el primer presidente de Chile?", "manuel blanco encalada"),
    ("¿En qué año se promulgó la Constitución actual?", "1980"),
    ("¿Quién fue el presidente derrocado en 1973?", "salvador allende"),
    ("¿En qué año volvió la democracia a Chile?", "1990"),
]

CHILE_NORMAL = [
    ("¿En qué año se fundó Santiago de Chile?", "1541"),
    ("¿Quién fundó Santiago de Chile?", "pedro de valdivia"),
    ("¿En qué año se creó la Capitanía General de Chile?", "1541"),
    ("¿Quién fue el primer gobernador de Chile?", "pedro de valdivia"),
    ("¿En qué año se produjo la batalla de Rancagua?", "1814"),
    ("¿Quién lideró la resistencia en Rancagua?", "bernardo o'higgins"),
    ("¿En qué año se produjo el Desastre de Rancagua?", "1814"),
    ("¿En qué año se cruzó la cordillera de los Andes?", "1817"),
    ("¿Quién lideró el cruce de los Andes?", "jose de san martin"),
    ("¿En qué año se produjo la batalla de Chacabuco?", "1817"),
    ("¿En qué año se produjo la batalla de Maipú?", "1818"),
    ("¿Quién fue el primer director supremo de Chile?", "bernardo o'higgins"),
    ("¿En qué año se abdicó O'Higgins?", "1823"),
    ("¿En qué año se promulgó la Constitución de 1833?", "1833"),
    ("¿Quién impulsó la Constitución de 1833?", "diego portales"),
    ("¿En qué año se produjo la guerra del Pacífico?", "1879"),
    ("¿Quién fue el presidente durante la guerra del Pacífico?", "anibal pinto"),
    ("¿En qué año se produjo la guerra civil chilena?", "1891"),
    ("¿En qué año se produjo el golpe militar en Chile?", "1973"),
    ("¿Quién lideró el golpe militar de 1973?", "augusto pinochet"),
]

CHILE_DIFICIL = [
    ("¿En qué año llegó Pedro de Valdivia a Chile?", "1540"),
    ("¿En qué año se fundó la ciudad de Concepción?", "1550"),
    ("¿Quién fundó Concepción?", "pedro de valdivia"),
    ("¿En qué año se produjo la batalla de Tucapel?", "1553"),
    ("¿Quién murió en la batalla de Tucapel?", "pedro de valdivia"),
    ("¿Quién fue el líder mapuche que venció en Tucapel?", "lautaro"),
    ("¿En qué año se produjo la batalla de Mataquito?", "1557"),
    ("¿Quién fue el gobernador de Chile en 1557?", "garcia hurtado de mendoza"),
    ("¿En qué año se creó la Real Audiencia de Chile?", "1565"),
    ("¿Quién fue el primer presidente de la Audiencia?", "melchor bravo de saravia"),
    ("¿En qué año se produjo la rebelión mapuche de 1598?", "1598"),
    ("¿Quién murió en la batalla de Curalaba?", "martin garcia onez de loyola"),
    ("¿En qué año se creó el ejército de Chile?", "1600"),
    ("¿En qué año se estableció el sistema de parlamentos?", "1641"),
    ("¿En qué año se creó la Universidad de San Felipe?", "1738"),
    ("¿En qué año se fundó la Academia de San Luis?", "1797"),
    ("¿En qué año se produjo la primera Junta Nacional?", "1810"),
    ("¿Quién presidió la primera Junta Nacional?", "mateo de toro zambrano"),
    ("¿En qué año se produjo el primer Congreso Nacional?", "1811"),
    ("¿Quién fue el primer presidente del Congreso Nacional?", "juan martinez de rozas"),
]

# ============================================================
# VENEZUELA
# ============================================================
VENEZUELA_FACIL = [
    ("¿Cuál es la capital de Venezuela?", "caracas"),
    ("¿En qué año se independizó Venezuela de España?", "1811"),
    ("¿Quién fue el libertador de Venezuela?", "simon bolivar"),
    ("¿Cómo se llama la moneda oficial de Venezuela?", "bolivar"),
    ("¿Qué país limita al oeste con Venezuela?", "colombia"),
    ("¿Qué país limita al este con Venezuela?", "brasil"),
    ("¿Cuál es el río más importante de Venezuela?", "orinoco"),
    ("¿En qué año se selló la independencia de Venezuela?", "1821"),
    ("¿Qué batalla selló la independencia de Venezuela?", "carabobo"),
    ("¿Quién nació en Venezuela y libertó varios países?", "simon bolivar"),
    ("¿Cuál es el salto de agua más alto del mundo?", "salto angel"),
    ("¿Quién fue el precursor de la independencia?", "francisco de miranda"),
    ("¿En qué año se creó la Gran Colombia?", "1819"),
    ("¿Cuál es el plato típico de Venezuela?", "arepa"),
    ("¿Qué escritor venezolano escribió 'Doña Bárbara'?", "romulo gallegos"),
    ("¿En qué año se abolió la esclavitud en Venezuela?", "1854"),
    ("¿Quién abolió la esclavitud en Venezuela?", "jose gregorio monagas"),
    ("¿En qué año se promulgó la Constitución actual?", "1999"),
    ("¿Quién fue el presidente entre 1999 y 2013?", "hugo chavez"),
    ("¿En qué año se descubrió petróleo en Venezuela?", "1914"),
]

VENEZUELA_NORMAL = [
    ("¿En qué año llegó Colón a Venezuela?", "1498"),
    ("¿En qué año se fundó Caracas?", "1567"),
    ("¿Quién fundó Caracas?", "diego de losada"),
    ("¿En qué año se creó la Capitanía General de Venezuela?", "1777"),
    ("¿Quién fue el primer capitán general de Venezuela?", "luis de unzaga"),
    ("¿En qué año se creó la Real Audiencia de Caracas?", "1786"),
    ("¿En qué año se produjo el movimiento de Gual y España?", "1797"),
    ("¿Quién lideró el movimiento de Gual y España?", "manuel gual"),
    ("¿En qué año se produjo la conspiración de los Mantuanos?", "1808"),
    ("¿En qué año se declaró la independencia de Venezuela?", "1811"),
    ("¿Quién firmó el Acta de Independencia?", "cristobal mendoza"),
    ("¿En qué año se produjo la caída de la Primera República?", "1812"),
    ("¿En qué año se produjo la batalla de Carabobo?", "1821"),
    ("¿Quién dirigió la batalla de Carabobo?", "simon bolivar"),
    ("¿En qué año se separó Venezuela de la Gran Colombia?", "1830"),
    ("¿Quién fue el primer presidente de Venezuela independiente?", "jose antonio paez"),
    ("¿En qué año se produjo la Revolución Liberal Restauradora?", "1899"),
    ("¿Quién lideró la Revolución Liberal Restauradora?", "cipriano castro"),
    ("¿En qué año se produjo el golpe contra Rómulo Gallegos?", "1948"),
    ("¿En qué año se firmó el Pacto de Puntofijo?", "1958"),
]

VENEZUELA_DIFICIL = [
    ("¿En qué año se fundó la ciudad de Coro?", "1527"),
    ("¿Quién fundó Coro?", "juan de ampies"),
    ("¿En qué año se creó la provincia de Venezuela?", "1528"),
    ("¿Quién fue el primer gobernador de Venezuela?", "ambrosio alfinger"),
    ("¿En qué año se fundó la ciudad de Valencia?", "1555"),
    ("¿Quién fundó Valencia?", "alonso diaz moreno"),
    ("¿En qué año se trasladó la capital de Coro a Caracas?", "1577"),
    ("¿Quién fue el primer gobernador de Caracas?", "juan de pimentel"),
    ("¿En qué año se creó la Compañía Guipuzcoana?", "1728"),
    ("¿En qué año se produjo la rebelión de Andresote?", "1730"),
    ("¿En qué año se produjo la rebelión de Juan Francisco de León?", "1749"),
    ("¿En qué año se creó la Intendencia de Caracas?", "1776"),
    ("¿Quién fue el primer intendente de Caracas?", "jose de abalos"),
    ("¿En qué año se produjo la Conspiración de Gual y España?", "1797"),
    ("¿Quién tradujo los Derechos del Hombre en Venezuela?", "juan german roscio"),
    ("¿En qué año se creó la Junta Suprema de Caracas?", "1810"),
    ("¿Quién presidió la Junta Suprema de Caracas?", "felipe fermin paul"),
    ("¿En qué año se produjo el terremoto de Caracas?", "1812"),
    ("¿En qué año se produjo la batalla de La Victoria?", "1814"),
    ("¿Quién dirigió la batalla de La Victoria?", "jose felix ribas"),
]

# ============================================================
# GUATEMALA
# ============================================================
GUATEMALA_FACIL = [
    ("¿Cuál es la capital de Guatemala?", "ciudad de guatemala"),
    ("¿En qué año se independizó Guatemala de España?", "1821"),
    ("¿Quién fue el prócer guatemalteco de la independencia?", "pedro molina"),
    ("¿Cómo se llama la moneda oficial de Guatemala?", "quetzal"),
    ("¿Qué país limita al norte con Guatemala?", "mexico"),
    ("¿Cuál es el volcán más alto de Guatemala?", "tajumulco"),
    ("¿En qué año se fundó la República de Guatemala?", "1847"),
    ("¿Quién fue el primer presidente de Guatemala?", "rafael carrera"),
    ("¿Qué cultura precolombina construyó Tikal?", "maya"),
    ("¿En qué año se firmó la paz en Guatemala?", "1996"),
    ("¿Cuál es el plato típico de Guatemala?", "tamales"),
    ("¿Qué idioma se habla en Guatemala?", "espanol"),
    ("¿En qué año se abolió la esclavitud en Guatemala?", "1824"),
    ("¿Quién fue el líder de la Revolución de Octubre?", "jacobo arbenz"),
    ("¿En qué año se produjo la Revolución de Octubre?", "1944"),
    ("¿Qué escritor guatemalteco ganó el Nobel?", "miguel angel asturias"),
    ("¿En qué año ganó Asturias el Nobel?", "1967"),
    ("¿Cuál es el lago más grande de Guatemala?", "atitlan"),
    ("¿En qué año se promulgó la Constitución actual?", "1985"),
    ("¿Qué presidente guatemalteco fue depuesto en 2015?", "otto perez molina"),
]

GUATEMALA_NORMAL = [
    ("¿En qué año se fundó la ciudad de Guatemala?", "1524"),
    ("¿Quién fundó la ciudad de Guatemala?", "pedro de alvarado"),
    ("¿En qué año se creó la Capitanía General de Guatemala?", "1542"),
    ("¿Quién fue el primer capitán general de Guatemala?", "alonso de maldonado"),
    ("¿En qué año se creó la Real Audiencia de Guatemala?", "1543"),
    ("¿Quién fue el primer presidente de la Audiencia?", "alonso de maldonado"),
    ("¿En qué año se trasladó la capital de Iximché?", "1527"),
    ("¿En qué año se fundó la Antigua Guatemala?", "1543"),
    ("¿En qué año se produjo el terremoto de Guatemala?", "1773"),
    ("¿En qué año se trasladó la capital a la Nueva Guatemala?", "1776"),
    ("¿En qué año se produjo la independencia de Guatemala?", "1821"),
    ("¿Quién firmó el Acta de Independencia?", "gabino gainza"),
    ("¿En qué año se anexó Guatemala a México?", "1822"),
    ("¿En qué año se separó Guatemala de México?", "1823"),
    ("¿En qué año se creó la Federación Centroamericana?", "1823"),
    ("¿Quién fue el primer presidente de la Federación?", "manuel jose arce"),
    ("¿En qué año se disolvió la Federación Centroamericana?", "1841"),
    ("¿En qué año se creó la República de Guatemala?", "1847"),
    ("¿En qué año se produjo la Revolución Liberal?", "1871"),
    ("¿Quién lideró la Revolución Liberal de 1871?", "justo rufino barrios"),
]

GUATEMALA_DIFICIL = [
    ("¿En qué año llegó Pedro de Alvarado a Guatemala?", "1524"),
    ("¿Quién fue el último gobernante maya de Guatemala?", "tecun uman"),
    ("¿En qué año se produjo la batalla de los Altos?", "1524"),
    ("¿En qué año se fundó la primera capital de Guatemala?", "1524"),
    ("¿Quién fue el primer obispo de Guatemala?", "francisco marroquin"),
    ("¿En qué año se creó la Universidad de San Carlos?", "1676"),
    ("¿Quién fundó la Universidad de San Carlos?", "carlos ii"),
    ("¿En qué año se creó la Capitanía General de Guatemala?", "1542"),
    ("¿Quién fue el primer capitán general de Guatemala?", "alonso de maldonado"),
    ("¿En qué año se creó la Audiencia de Guatemala?", "1543"),
    ("¿En qué año se produjo la independencia de Guatemala?", "1821"),
    ("¿Quién fue el primer jefe de estado de Guatemala?", "mariano rivera paz"),
    ("¿En qué año se creó el Estado de Guatemala?", "1824"),
    ("¿En qué año se produjo la guerra de los montañeses?", "1837"),
    ("¿Quién lideró la guerra de los montañeses?", "rafael carrera"),
    ("¿En qué año se proclamó la República de Guatemala?", "1847"),
    ("¿En qué año se produjo la Reforma Liberal?", "1871"),
    ("¿Quién impulsó la Reforma Liberal?", "justo rufino barrios"),
    ("¿En qué año se creó el Banco de Guatemala?", "1945"),
    ("¿En qué año se produjo el golpe contra Arbenz?", "1954"),
]

# ============================================================
# HONDURAS
# ============================================================
HONDURAS_FACIL = [
    ("¿Cuál es la capital de Honduras?", "tegucigalpa"),
    ("¿En qué año se independizó Honduras de España?", "1821"),
    ("¿Quién fue el prócer hondureño de la independencia?", "jose cecilio del valle"),
    ("¿Cómo se llama la moneda oficial de Honduras?", "lempira"),
    ("¿Qué país limita al oeste con Honduras?", "guatemala"),
    ("¿Qué país limita al sur con Honduras?", "nicaragua"),
    ("¿Cuál es el río más largo de Honduras?", "ulua"),
    ("¿En qué año se fundó la República de Honduras?", "1838"),
    ("¿Quién fue el primer presidente de Honduras?", "dionisio de herrera"),
    ("¿Qué cultura precolombina construyó Copán?", "maya"),
    ("¿Cuál es el plato típico de Honduras?", "baleada"),
    ("¿Qué idioma se habla en Honduras?", "espanol"),
    ("¿En qué año se abolió la esclavitud en Honduras?", "1824"),
    ("¿Quién impulsó la reforma liberal en Honduras?", "marco aurelio soto"),
    ("¿En qué año se produjo la Reforma Liberal?", "1876"),
    ("¿Qué escritora hondureña escribió 'Blanca Olmedo'?", "lucila gamero de medina"),
    ("¿En qué año se creó el Banco Central de Honduras?", "1950"),
    ("¿Cuál es la isla más famosa de Honduras?", "roatan"),
    ("¿En qué año se promulgó la Constitución actual?", "1982"),
    ("¿Qué presidente hondureño fue depuesto en 2009?", "manuel zelaya"),
]

HONDURAS_NORMAL = [
    ("¿En qué año llegó Colón a Honduras?", "1502"),
    ("¿En qué año se fundó la ciudad de Comayagua?", "1537"),
    ("¿Quién fundó Comayagua?", "alonso de caceres"),
    ("¿En qué año se creó la Provincia de Honduras?", "1524"),
    ("¿Quién fue el primer gobernador de Honduras?", "hernan cortes"),
    ("¿En qué año se creó la Real Audiencia de los Confines?", "1543"),
    ("¿Quién fue el primer presidente de la Audiencia?", "alonso de maldonado"),
    ("¿En qué año se trasladó la capital de Gracias a Comayagua?", "1545"),
    ("¿En qué año se produjo la independencia de Honduras?", "1821"),
    ("¿Quién firmó el Acta de Independencia?", "jose cecilio del valle"),
    ("¿En qué año se anexó Honduras a México?", "1822"),
    ("¿En qué año se separó Honduras de México?", "1823"),
    ("¿En qué año se creó el Estado de Honduras?", "1824"),
    ("¿Quién fue el primer jefe de estado de Honduras?", "dionisio de herrera"),
    ("¿En qué año se separó Honduras de la Federación?", "1838"),
    ("¿En qué año se produjo la guerra del fútbol?", "1969"),
    ("¿Quién fue el presidente durante la guerra del fútbol?", "oswaldo lopez arellano"),
    ("¿En qué año se creó el Partido Liberal de Honduras?", "1891"),
    ("¿Quién fundó el Partido Liberal de Honduras?", "policarpo bonilla"),
    ("¿En qué año se produjo el golpe de estado en Honduras?", "2009"),
]

HONDURAS_DIFICIL = [
    ("¿En qué año llegó Hernán Cortés a Honduras?", "1524"),
    ("¿Quién fue el último cacique indígena de Honduras?", "lempira"),
    ("¿En qué año se produjo la batalla contra Lempira?", "1537"),
    ("¿En qué año se fundó la ciudad de Trujillo?", "1525"),
    ("¿Quién fundó Trujillo?", "hernan cortes"),
    ("¿En qué año se fundó la ciudad de Gracias?", "1536"),
    ("¿Quién fundó Gracias?", "gonzalo de alvarado"),
    ("¿En qué año se creó la Capitanía General de Guatemala?", "1542"),
    ("¿En qué año se fundó la Universidad de Honduras?", "1847"),
    ("¿Quién fundó la Universidad de Honduras?", "jose trinidad reyes"),
    ("¿En qué año se creó el Banco de Honduras?", "1888"),
    ("¿En qué año se produjo la Revolución Liberal en Honduras?", "1876"),
    ("¿Quién lideró la Revolución Liberal de 1876?", "marco aurelio soto"),
    ("¿En qué año se creó la República de Honduras?", "1838"),
    ("¿En qué año se promulgó la Constitución de Honduras?", "1982"),
    ("¿En qué año se creó el ejército de Honduras?", "1825"),
    ("¿En qué año se fundó el Partido Nacional de Honduras?", "1902"),
    ("¿Quién fundó el Partido Nacional de Honduras?", "manuel bonilla"),
    ("¿En qué año se creó la UNAH?", "1957"),
    ("¿En qué año se firmó el Tratado de Paz con El Salvador?", "1980"),
]

# ============================================================
# COSTA RICA
# ============================================================
COSTA_RICA_FACIL = [
    ("¿Cuál es la capital de Costa Rica?", "san jose"),
    ("¿En qué año se independizó Costa Rica de España?", "1821"),
    ("¿Quién fue el prócer costarricense de la independencia?", "jose maria castro madriz"),
    ("¿Cómo se llama la moneda oficial de Costa Rica?", "colon"),
    ("¿Qué país limita al norte con Costa Rica?", "nicaragua"),
    ("¿Qué país limita al sur con Costa Rica?", "panama"),
    ("¿Cuántos océanos bañan Costa Rica?", "dos"),
    ("¿En qué año se fundó la República de Costa Rica?", "1848"),
    ("¿Quién fue el primer presidente de Costa Rica?", "jose maria castro madriz"),
    ("¿Qué país no tiene ejército desde 1948?", "costa rica"),
    ("¿Cuál es el plato típico de Costa Rica?", "gallo pinto"),
    ("¿Qué idioma se habla en Costa Rica?", "espanol"),
    ("¿En qué año se abolió la esclavitud en Costa Rica?", "1824"),
    ("¿Quién abolió el ejército en Costa Rica?", "jose figueres ferrer"),
    ("¿En qué año se abolió el ejército en Costa Rica?", "1948"),
    ("¿Qué premio Nobel de la Paz es costarricense?", "oscar arias sanchez"),
    ("¿En qué año ganó Óscar Arias el Nobel?", "1987"),
    ("¿Cuál es el volcán más famoso de Costa Rica?", "arenal"),
    ("¿En qué año se promulgó la Constitución actual?", "1949"),
    ("¿Qué presidente costarricense ganó el Nobel de la Paz?", "oscar arias"),
]

COSTA_RICA_NORMAL = [
    ("¿En qué año llegó Colón a Costa Rica?", "1502"),
    ("¿En qué año se fundó la ciudad de Cartago?", "1563"),
    ("¿Quién fundó Cartago?", "juan vasquez de coronado"),
    ("¿En qué año se creó la Provincia de Costa Rica?", "1573"),
    ("¿Quién fue el primer gobernador de Costa Rica?", "diego de artieda"),
    ("¿En qué año se produjo la independencia de Costa Rica?", "1821"),
    ("¿Quién firmó el Acta de Independencia?", "jose maria castro madriz"),
    ("¿En qué año se anexó Costa Rica a México?", "1822"),
    ("¿En qué año se separó Costa Rica de México?", "1823"),
    ("¿En qué año se creó el Estado de Costa Rica?", "1824"),
    ("¿Quién fue el primer jefe de estado de Costa Rica?", "juan mora fernandez"),
    ("¿En qué año se separó Costa Rica de la Federación?", "1838"),
    ("¿En qué año se proclamó la República de Costa Rica?", "1848"),
    ("¿Quién impulsó la educación en Costa Rica?", "jose maria castro madriz"),
    ("¿En qué año se produjo la guerra civil costarricense?", "1948"),
    ("¿Quién lideró el bando ganador?", "jose figueres ferrer"),
    ("¿En qué año se promulgó la Constitución?", "1949"),
    ("¿En qué año se creó el Banco Central?", "1950"),
    ("¿En qué año se firmó el TLC con EE.UU.?", "2004"),
    ("¿En qué año se aprobó el matrimonio igualitario?", "2020"),
]

COSTA_RICA_DIFICIL = [
    ("¿En qué año llegó Juan Vásquez de Coronado?", "1562"),
    ("¿Quién fue el primer gobernador de Costa Rica?", "diego de artieda"),
    ("¿En qué año se fundó la ciudad de Esparza?", "1577"),
    ("¿Quién fundó Esparza?", "diego de artieda"),
    ("¿En qué año se fundó la ciudad de Heredia?", "1706"),
    ("¿Quién fundó Heredia?", "jose antonio de ori"),
    ("¿En qué año se fundó la ciudad de Alajuela?", "1782"),
    ("¿En qué año se creó la Casa de Enseñanza?", "1814"),
    ("¿Quién fundó la Casa de Enseñanza?", "jose maria castro madriz"),
    ("¿En qué año se creó la Universidad de Santo Tomás?", "1843"),
    ("¿Quién fundó la Universidad de Santo Tomás?", "jose maria castro madriz"),
    ("¿En qué año se creó el Banco Anglo-Costarricense?", "1863"),
    ("¿En qué año se creó el Banco de Costa Rica?", "1877"),
    ("¿En qué año se produjo la dictadura de Tinoco?", "1917"),
    ("¿Quién fue el dictador costarricense de 1917?", "federico tinoco"),
    ("¿En qué año se produjo la Revolución de 1948?", "1948"),
    ("¿Quién fue el presidente depuesto en 1948?", "rafael angel calderon guardia"),
    ("¿En qué año se fundó el Partido Liberación Nacional?", "1951"),
    ("¿Quién fundó el Partido Liberación Nacional?", "jose figueres ferrer"),
    ("¿En qué año se firmó el TLC con Centroamérica?", "2004"),
]

# ============================================================
# PANAMÁ
# ============================================================
PANAMA_FACIL = [
    ("¿Cuál es la capital de Panamá?", "ciudad de panama"),
    ("¿En qué año se independizó Panamá de España?", "1821"),
    ("¿De qué país se separó Panamá en 1903?", "colombia"),
    ("¿Cómo se llama la moneda oficial de Panamá?", "balboa"),
    ("¿Qué país limita al oeste con Panamá?", "costa rica"),
    ("¿Qué país limita al este con Panamá?", "colombia"),
    ("¿Qué canal famoso atraviesa Panamá?", "canal de panama"),
    ("¿En qué año se inauguró el Canal de Panamá?", "1914"),
    ("¿Quién fue el prócer panameño de la independencia?", "jose de f brea"),
    ("¿Qué país construyó el Canal de Panamá?", "estados unidos"),
    ("¿Cuál es el plato típico de Panamá?", "sancocho"),
    ("¿Qué idioma se habla en Panamá?", "espanol"),
    ("¿En qué año se abolió la esclavitud en Panamá?", "1851"),
    ("¿Quién fue el primer presidente de Panamá?", "manuel amador guerrero"),
    ("¿En qué año se firmó el Tratado Hay-Bunau Varilla?", "1903"),
    ("¿En qué año se firmaron los Tratados Torrijos-Carter?", "1977"),
    ("¿Quién firmó los Tratados Torrijos-Carter?", "omar torrijos"),
    ("¿En qué año se transfirió el Canal a Panamá?", "1999"),
    ("¿En qué año se promulgó la Constitución actual?", "1972"),
    ("¿Qué presidente panameño fue depuesto en 1989?", "manuel antonio noriega"),
]

PANAMA_NORMAL = [
    ("¿En qué año llegó Colón a Panamá?", "1502"),
    ("¿En qué año se fundó la ciudad de Panamá?", "1519"),
    ("¿Quién fundó la ciudad de Panamá?", "pedro arias davila"),
    ("¿En qué año se creó la Real Audiencia de Panamá?", "1538"),
    ("¿Quién fue el primer presidente de la Audiencia?", "francisco perez de robles"),
    ("¿En qué año se produjo el ataque de Henry Morgan?", "1671"),
    ("¿En qué año se trasladó la ciudad de Panamá?", "1673"),
    ("¿En qué año se produjo la independencia de Panamá?", "1821"),
    ("¿Quién firmó el Acta de Independencia?", "jose de f brea"),
    ("¿En qué año se anexó Panamá a la Gran Colombia?", "1821"),
    ("¿En qué año se separó Panamá de Colombia?", "1903"),
    ("¿Quién fue el primer presidente de Panamá?", "manuel amador guerrero"),
    ("¿En qué año se construyó el ferrocarril transístmico?", "1855"),
    ("¿En qué año fracasó el intento francés del canal?", "1889"),
    ("¿Quién lideró el intento francés del canal?", "ferdinand de lesseps"),
    ("¿En qué año se inició la construcción por EE.UU.?", "1904"),
    ("¿En qué año se inauguró el Canal de Panamá?", "1914"),
    ("¿En qué año se firmó el Tratado Remón-Eisenhower?", "1955"),
    ("¿En qué año se produjo el golpe contra Arnulfo Arias?", "1968"),
    ("¿Quién lideró el golpe de 1968 en Panamá?", "omar torrijos"),
]

PANAMA_DIFICIL = [
    ("¿En qué año llegó Rodrigo de Bastidas a Panamá?", "1501"),
    ("¿En qué año se fundó Santa María la Antigua del Darién?", "1510"),
    ("¿Quién fundó Santa María la Antigua del Darién?", "martin fernandez de enciso"),
    ("¿En qué año se creó la Gobernación de Castilla del Oro?", "1513"),
    ("¿Quién fue el primer gobernador de Castilla del Oro?", "pedro arias davila"),
    ("¿En qué año descubrió Balboa el Mar del Sur?", "1513"),
    ("¿En qué año se fundó la ciudad de Nombre de Dios?", "1510"),
    ("¿En qué año se fundó Portobelo?", "1597"),
    ("¿En qué año se creó la Audiencia de Panamá?", "1538"),
    ("¿En qué año se creó la Real Audiencia de Panamá?", "1563"),
    ("¿En qué año se trasladó la Audiencia de Panamá?", "1563"),
    ("¿En qué año se produjo el terremoto de Panamá?", "1621"),
    ("¿En qué año se produjo la independencia de Panamá?", "1821"),
    ("¿En qué año se creó el Estado de Panamá?", "1821"),
    ("¿En qué año se firmó el Tratado Herrán-Hay?", "1903"),
    ("¿Quién firmó el Tratado Herrán-Hay por Panamá?", "philippe bunau-varilla"),
    ("¿En qué año se firmó el Tratado Hay-Bunau Varilla?", "1903"),
    ("¿En qué año se firmó el Tratado Arias-Roosevelt?", "1936"),
    ("¿En qué año se firmó el Tratado de 1955?", "1955"),
    ("¿En qué año se produjo la invasión de EE.UU. a Panamá?", "1989"),
]

# ============================================================
# BOLIVIA
# ============================================================
BOLIVIA_FACIL = [
    ("¿Cuál es la capital constitucional de Bolivia?", "sucre"),
    ("¿Cuál es la sede del gobierno de Bolivia?", "la paz"),
    ("¿En qué año se independizó Bolivia de España?", "1825"),
    ("¿Quién fue el libertador de Bolivia?", "simon bolivar"),
    ("¿Cómo se llama la moneda oficial de Bolivia?", "boliviano"),
    ("¿Qué país limita al oeste con Bolivia?", "peru"),
    ("¿Qué país limita al este con Bolivia?", "brasil"),
    ("¿Cuál es el lago más famoso de Bolivia?", "titicaca"),
    ("¿En qué año se fundó la República de Bolivia?", "1825"),
    ("¿Quién fue el primer presidente de Bolivia?", "antonio jose de sucre"),
    ("¿Qué cultura precolombina habitó Bolivia?", "tiwanaku"),
    ("¿Cuál es el plato típico de Bolivia?", "salteña"),
    ("¿Qué idioma se habla en Bolivia?", "espanol"),
    ("¿En qué año se abolió la esclavitud en Bolivia?", "1826"),
    ("¿Quién impulsó la educación en Bolivia?", "andres de santa cruz"),
    ("¿En qué año se perdió el Litoral boliviano?", "1879"),
    ("¿En qué guerra perdió Bolivia su salida al mar?", "guerra del pacifico"),
    ("¿Qué presidente nacionalizó el estaño?", "victor paz estenssoro"),
    ("¿En qué año se promulgó la Constitución actual?", "2009"),
    ("¿Qué presidente boliviano renunció en 2019?", "evo morales"),
]

BOLIVIA_NORMAL = [
    ("¿En qué año se fundó la ciudad de Sucre?", "1538"),
    ("¿Quién fundó Sucre?", "pedro de anzuress"),
    ("¿En qué año se creó la Real Audiencia de Charcas?", "1559"),
    ("¿Quién fue el primer presidente de la Audiencia?", "pedro ramirez de quiñones"),
    ("¿En qué año se fundó la ciudad de La Paz?", "1548"),
    ("¿Quién fundó La Paz?", "alonso de mendoza"),
    ("¿En qué año se produjo la rebelión de Túpac Katari?", "1781"),
    ("¿Quién fue Túpac Katari?", "julian apaza"),
    ("¿En qué año se produjo la rebelión de Túpac Amaru II?", "1780"),
    ("¿En qué año se produjo la independencia de Bolivia?", "1825"),
    ("¿Quién firmó el Acta de Independencia?", "jose mariano serrano"),
    ("¿En qué año se creó la Confederación Perú-Boliviana?", "1836"),
    ("¿Quién fue el protector de la Confederación?", "andres de santa cruz"),
    ("¿En qué año se disolvió la Confederación?", "1839"),
    ("¿En qué año se produjo la guerra del Pacífico?", "1879"),
    ("¿Quién fue el presidente durante la guerra del Pacífico?", "hilario daza"),
    ("¿En qué año se firmó el Tratado de Ancón?", "1883"),
    ("¿En qué año se produjo la guerra del Chaco?", "1932"),
    ("¿Quién fue el presidente durante la guerra del Chaco?", "daniel salamanca"),
    ("¿En qué año se firmó la paz con Paraguay?", "1938"),
]

BOLIVIA_DIFICIL = [
    ("¿En qué año llegó Diego de Almagro a Bolivia?", "1535"),
    ("¿En qué año se fundó Potosí?", "1545"),
    ("¿Quién fundó Potosí?", "juan de villarroel"),
    ("¿En qué año se creó la Casa de la Moneda de Potosí?", "1572"),
    ("¿En qué año se creó la Audiencia de Charcas?", "1559"),
    ("¿En qué año se trasladó la Audiencia a Sucre?", "1561"),
    ("¿En qué año se creó el Obispado de La Paz?", "1605"),
    ("¿En qué año se produjo la sublevación de los Katari?", "1781"),
    ("¿Quién fue el líder aimara de 1781?", "tupac katari"),
    ("¿En qué año se produjo la Revolución de Chuquisaca?", "1809"),
    ("¿Quién lideró la Revolución de Chuquisaca?", "jaime de zudanez"),
    ("¿En qué año se produjo la Revolución de La Paz?", "1809"),
    ("¿Quién lideró la Revolución de La Paz?", "pedro domingo murillo"),
    ("¿En qué año se creó la República de Bolivia?", "1825"),
    ("¿Quién fue el primer presidente de Bolivia?", "antonio jose de sucre"),
    ("¿En qué año se promulgó la primera Constitución?", "1826"),
    ("¿En qué año se creó la Confederación Perú-Boliviana?", "1836"),
    ("¿En qué año se produjo la batalla de Yungay?", "1839"),
    ("¿En qué año se creó el Banco Central de Bolivia?", "1928"),
    ("¿En qué año se produjo la Revolución Nacional?", "1952"),
]

# ============================================================
# PARAGUAY
# ============================================================
PARAGUAY_FACIL = [
    ("¿Cuál es la capital de Paraguay?", "asuncion"),
    ("¿En qué año se independizó Paraguay de España?", "1811"),
    ("¿Quién fue el prócer paraguayo de la independencia?", "gaspar rodriguez de francia"),
    ("¿Cómo se llama la moneda oficial de Paraguay?", "guarani"),
    ("¿Qué país limita al oeste con Paraguay?", "bolivia"),
    ("¿Qué país limita al este con Paraguay?", "brasil"),
    ("¿Cuál es el río más importante de Paraguay?", "paraguay"),
    ("¿En qué año se fundó la República de Paraguay?", "1811"),
    ("¿Quién fue el primer presidente de Paraguay?", "gaspar rodriguez de francia"),
    ("¿Qué cultura precolombina habitó Paraguay?", "guarani"),
    ("¿Cuál es el plato típico de Paraguay?", "sopa paraguaya"),
    ("¿Qué idioma se habla en Paraguay?", "espanol y guarani"),
    ("¿En qué año se abolió la esclavitud en Paraguay?", "1842"),
    ("¿Quién impulsó la educación en Paraguay?", "carlos antonio lopez"),
    ("¿En qué año se produjo la guerra de la Triple Alianza?", "1864"),
    ("¿Quién fue el presidente durante la Triple Alianza?", "francisco solano lopez"),
    ("¿En qué año terminó la guerra de la Triple Alianza?", "1870"),
    ("¿En qué año se produjo la guerra del Chaco?", "1932"),
    ("¿En qué año se firmó la paz con Bolivia?", "1938"),
    ("¿Qué presidente paraguayo fue derrocado en 2012?", "fernando lugo"),
]

PARAGUAY_NORMAL = [
    ("¿En qué año llegó Aleixo Garcia a Paraguay?", "1524"),
    ("¿En qué año se fundó Asunción?", "1537"),
    ("¿Quién fundó Asunción?", "juan de salazar"),
    ("¿En qué año se creó la Gobernación del Paraguay?", "1537"),
    ("¿Quién fue el primer gobernador de Paraguay?", "domingo martinez de irala"),
    ("¿En qué año se creó la Real Audiencia de Paraguay?", "1564"),
    ("¿En qué año se produjo la Revolución de los Comuneros?", "1721"),
    ("¿Quién lideró la Revolución de los Comuneros?", "jose de antequera"),
    ("¿En qué año se produjo la independencia de Paraguay?", "1811"),
    ("¿Quién firmó el Acta de Independencia?", "pedro juan caballero"),
    ("¿En qué año se creó la República de Paraguay?", "1813"),
    ("¿En qué año se proclamó la dictadura de Francia?", "1816"),
    ("¿Quién fue el dictador entre 1816 y 1840?", "gaspar rodriguez de francia"),
    ("¿En qué año se produjo la guerra de la Triple Alianza?", "1864"),
    ("¿Quiénes formaron la Triple Alianza?", "brasil argentina y uruguay"),
    ("¿En qué año se produjo la batalla de Tuyutí?", "1866"),
    ("¿En qué año se produjo la batalla de Curupaytí?", "1866"),
    ("¿En qué año murió Francisco Solano López?", "1870"),
    ("¿En qué año se firmó la paz con Bolivia?", "1938"),
    ("¿En qué año se produjo la dictadura de Stroessner?", "1954"),
]

PARAGUAY_DIFICIL = [
    ("¿En qué año llegó Juan de Salazar a Paraguay?", "1537"),
    ("¿Quién fundó la ciudad de Asunción?", "juan de salazar"),
    ("¿En qué año se creó el Cabildo de Asunción?", "1541"),
    ("¿En qué año se produjo la rebelión de los comuneros?", "1721"),
    ("¿Quién fue el líder comunero de 1721?", "jose de antequera"),
    ("¿En qué año se produjo la revolución comunera de 1731?", "1731"),
    ("¿Quién fue el gobernador depuesto en 1731?", "agustin de ruiloba"),
    ("¿En qué año se creó el Obispado de Asunción?", "1547"),
    ("¿En qué año se produjo la independencia de Paraguay?", "1811"),
    ("¿Quién firmó el Acta de Independencia?", "gaspar rodriguez de francia"),
    ("¿En qué año se produjo la primera Junta de Gobierno?", "1811"),
    ("¿En qué año se produjo el Congreso de 1813?", "1813"),
    ("¿En qué año se proclamó la República de Paraguay?", "1813"),
    ("¿En qué año se creó el Consulado de Paraguay?", "1813"),
    ("¿En qué año se proclamó la dictadura de Francia?", "1816"),
    ("¿En qué año se firmó el Tratado de la Triple Alianza?", "1865"),
    ("¿En qué año se produjo la batalla de Riachuelo?", "1865"),
    ("¿En qué año se produjo la batalla de Tuyutí?", "1866"),
    ("¿En qué año se produjo la batalla de Curupaytí?", "1866"),
    ("¿En qué año se produjo la batalla de Cerro Corá?", "1870"),
]

# ============================================================
# URUGUAY
# ============================================================
URUGUAY_FACIL = [
    ("¿Cuál es la capital de Uruguay?", "montevideo"),
    ("¿En qué año se independizó Uruguay de Brasil?", "1825"),
    ("¿Quién fue el prócer uruguayo de la independencia?", "jose gervasio artigas"),
    ("¿Cómo se llama la moneda oficial de Uruguay?", "peso uruguayo"),
    ("¿Qué país limita al oeste con Uruguay?", "argentina"),
    ("¿Qué país limita al norte con Uruguay?", "brasil"),
    ("¿Cuál es el río más importante de Uruguay?", "uruguay"),
    ("¿En qué año se fundó la República de Uruguay?", "1825"),
    ("¿Quién fue el primer presidente de Uruguay?", "fructuoso rivera"),
    ("¿Qué cultura precolombina habitó Uruguay?", "charrua"),
    ("¿Cuál es el plato típico de Uruguay?", "chivito"),
    ("¿Qué idioma se habla en Uruguay?", "espanol"),
    ("¿En qué año se abolió la esclavitud en Uruguay?", "1842"),
    ("¿Quién impulsó la educación en Uruguay?", "jose batlle y ordonez"),
    ("¿En qué año se produjo la guerra del Paraguay?", "1864"),
    ("¿En qué año se promulgó la Constitución actual?", "1967"),
    ("¿En qué año ganó Uruguay su primer mundial?", "1930"),
    ("¿En qué año se produjo la dictadura uruguaya?", "1973"),
    ("¿En qué año volvió la democracia a Uruguay?", "1985"),
    ("¿Qué presidente uruguayo impulsó la legalización de la marihuana?", "jose mujica"),
]

URUGUAY_NORMAL = [
    ("¿En qué año llegó Juan Díaz de Solís a Uruguay?", "1516"),
    ("¿En qué año se fundó Montevideo?", "1726"),
    ("¿Quién fundó Montevideo?", "bruno mauricio de zabala"),
    ("¿En qué año se creó la Banda Oriental?", "1724"),
    ("¿Quién fue el primer gobernador de la Banda Oriental?", "bruno mauricio de zabala"),
    ("¿En qué año se produjo el Éxodo Oriental?", "1811"),
    ("¿Quién lideró el Éxodo Oriental?", "jose gervasio artigas"),
    ("¿En qué año se produjo la independencia de Uruguay?", "1825"),
    ("¿Quién firmó el Acta de Independencia?", "juan antonio lavalleja"),
    ("¿En qué año se creó la República de Uruguay?", "1825"),
    ("¿En qué año se produjo la guerra del Brasil?", "1825"),
    ("¿En qué año se firmó la Convención Preliminar de Paz?", "1828"),
    ("¿En qué año se promulgó la primera Constitución?", "1830"),
    ("¿Quién fue el primer presidente de Uruguay?", "fructuoso rivera"),
    ("¿En qué año se produjo la guerra Grande?", "1839"),
    ("¿Quién fue el líder del Partido Blanco?", "manuel oribe"),
    ("¿Quién fue el líder del Partido Colorado?", "fructuoso rivera"),
    ("¿En qué año se produjo la Revolución de las Lanzas?", "1870"),
    ("¿Quién lideró la Revolución de las Lanzas?", "timoteo aparicio"),
    ("¿En qué año se produjo el golpe de estado de Terra?", "1933"),
]

URUGUAY_DIFICIL = [
    ("¿En qué año llegó Juan Díaz de Solís al Río de la Plata?", "1516"),
    ("¿Quién fundó la primera ciudad en Uruguay?", "juan de sanabria"),
    ("¿En qué año se fundó Colonia del Sacramento?", "1680"),
    ("¿Quién fundó Colonia del Sacramento?", "manuel lopo de faria"),
    ("¿En qué año se creó la Gobernación de Montevideo?", "1751"),
    ("¿Quién fue el primer gobernador de Montevideo?", "jose joaquin de viana"),
    ("¿En qué año se produjo la ocupación inglesa?", "1807"),
    ("¿Quién lideró la defensa de Montevideo en 1807?", "santiago de liniers"),
    ("¿En qué año se produjo el Grito de Asencio?", "1811"),
    ("¿Quién lideró el Grito de Asencio?", "pedro jose vieira"),
    ("¿En qué año se produjo la batalla de Las Piedras?", "1811"),
    ("¿Quién dirigió la batalla de Las Piedras?", "jose gervasio artigas"),
    ("¿En qué año se creó la Liga Federal?", "1815"),
    ("¿Quién fue el protector de la Liga Federal?", "jose gervasio artigas"),
    ("¿En qué año se produjo la invasión portuguesa?", "1816"),
    ("¿En qué año se creó la Provincia Cisplatina?", "1821"),
    ("¿En qué año se produjo el desembarco de los 33 Orientales?", "1825"),
    ("¿Quién lideró a los 33 Orientales?", "juan antonio lavalleja"),
    ("¿En qué año se firmó la Convención Preliminar de Paz?", "1828"),
    ("¿En qué año se creó el Banco de la República?", "1896"),
]

# ============================================================
# REPÚBLICA DOMINICANA
# ============================================================
REP_DOMINICANA_FACIL = [
    ("¿Cuál es la capital de República Dominicana?", "santo domingo"),
    ("¿En qué año se independizó de Haití?", "1844"),
    ("¿Quién fue el prócer dominicano de la independencia?", "juan pablo duarte"),
    ("¿Cómo se llama la moneda oficial?", "peso dominicano"),
    ("¿Qué país limita al oeste con República Dominicana?", "haiti"),
    ("¿Qué océano baña las costas?", "atlantico"),
    ("¿Cuál es el pico más alto del Caribe?", "pico duarte"),
    ("¿En qué año se fundó la República Dominicana?", "1844"),
    ("¿Quién fue el primer presidente?", "pedro santana"),
    ("¿Qué cultura precolombina habitó la isla?", "taina"),
    ("¿Cuál es el plato típico?", "sancocho"),
    ("¿Qué idioma se habla?", "espanol"),
    ("¿En qué año se abolió la esclavitud?", "1822"),
    ("¿Quién impulsó la educación dominicana?", "juan bosch"),
    ("¿En qué año se produjo la Restauración?", "1863"),
    ("¿Quién fue el dictador entre 1930 y 1961?", "rafael leonidas trujillo"),
    ("¿En qué año fue asesinado Trujillo?", "1961"),
    ("¿En qué año se produjo la guerra civil?", "1965"),
    ("¿En qué año se promulgó la Constitución actual?", "2015"),
    ("¿Qué escritor dominicano ganó el Premio Cervantes?", "juan bosch"),
]

REP_DOMINICANA_NORMAL = [
    ("¿En qué año llegó Colón a la isla?", "1492"),
    ("¿En qué año se fundó Santo Domingo?", "1498"),
    ("¿Quién fundó Santo Domingo?", "bartolome colon"),
    ("¿En qué año se creó la Real Audiencia de Santo Domingo?", "1511"),
    ("¿Quién fue el primer presidente de la Audiencia?", "marcos de aguilar"),
    ("¿En qué año se produjo la rebelión de Enriquillo?", "1519"),
    ("¿Quién fue Enriquillo?", "guarocuya"),
    ("¿En qué año se firmó el Tratado de Basilea?", "1795"),
    ("¿En qué año se produjo la independencia de Haití?", "1804"),
    ("¿En qué año se produjo la independencia efímera?", "1821"),
    ("¿Quién lideró la independencia efímera?", "jose nuñez de cespedes"),
    ("¿En qué año se produjo la ocupación haitiana?", "1822"),
    ("¿Quién fue el presidente de Haití que ocupó Santo Domingo?", "jean pierre boyer"),
    ("¿En qué año se produjo la independencia definitiva?", "1844"),
    ("¿Quién firmó el Acta de Independencia?", "francisco del rosario sanchez"),
    ("¿En qué año se produjo la anexión a España?", "1861"),
    ("¿Quién fue el presidente que anexó el país a España?", "pedro santana"),
    ("¿En qué año se produjo la guerra de la Restauración?", "1863"),
    ("¿Quién fue el líder de la Restauración?", "gregorio luperon"),
    ("¿En qué año se produjo la intervención de EE.UU.?", "1916"),
]

REP_DOMINICANA_DIFICIL = [
    ("¿En qué año llegó Colón a La Española?", "1492"),
    ("¿Quién fue el primer gobernador de La Española?", "nicolas de ovando"),
    ("¿En qué año se fundó la ciudad de Santo Domingo?", "1496"),
    ("¿Quién fundó Santo Domingo?", "bartolome colon"),
    ("¿En qué año se creó la Real Audiencia de Santo Domingo?", "1511"),
    ("¿Quién fue el primer presidente de la Audiencia?", "marcos de aguilar"),
    ("¿En qué año se produjo la rebelión de Enriquillo?", "1519"),
    ("¿En qué año se produjo la devastación de Osorio?", "1605"),
    ("¿Quién ordenó la devastación de Osorio?", "antonio de osorio"),
    ("¿En qué año se firmó el Tratado de Ryswick?", "1697"),
    ("¿En qué año se firmó el Tratado de Aranjuez?", "1777"),
    ("¿En qué año se firmó el Tratado de Basilea?", "1795"),
    ("¿En qué año se produjo la invasión de Toussaint?", "1801"),
    ("¿En qué año se produjo la batalla de Palo Hincado?", "1808"),
    ("¿Quién lideró la batalla de Palo Hincado?", "juan sanchez ramirez"),
    ("¿En qué año se produjo la reconquista española?", "1809"),
    ("¿En qué año se produjo la independencia efímera?", "1821"),
    ("¿Quién lideró la independencia efímera?", "jose nuñez de cespedes"),
    ("¿En qué año se produjo la independencia definitiva?", "1844"),
    ("¿En qué año se promulgó la primera Constitución?", "1844"),
]

# ============================================================
# PUERTO RICO
# ============================================================
PUERTO_RICO_FACIL = [
    ("¿Cuál es la capital de Puerto Rico?", "san juan"),
    ("¿A qué país pertenece Puerto Rico actualmente?", "estados unidos"),
    ("¿En qué año llegó Colón a Puerto Rico?", "1493"),
    ("¿Cómo se llama la moneda oficial?", "dolar"),
    ("¿Qué océano baña las costas?", "atlantico"),
    ("¿Cuál es el idioma oficial?", "espanol e ingles"),
    ("¿Qué cultura precolombina habitó Puerto Rico?", "taina"),
    ("¿En qué año se fundó San Juan?", "1521"),
    ("¿Quién fue el conquistador de Puerto Rico?", "juan ponce de leon"),
    ("¿Cuál es el plato típico?", "mofongo"),
    ("¿Qué escritor puertorriqueño escribió 'La Guaracha del Macho Camacho'?", "luis rafael sanchez"),
    ("¿En qué año se abolió la esclavitud?", "1873"),
    ("¿En qué año se cedió Puerto Rico a EE.UU.?", "1898"),
    ("¿En qué año se otorgó la ciudadanía estadounidense?", "1917"),
    ("¿En qué año se promulgó la Constitución?", "1952"),
    ("¿Quién fue el primer gobernador electo?", "luis muñoz marin"),
    ("¿En qué año se fundó el Partido Popular Democrático?", "1938"),
    ("¿Qué cantante puertorriqueño es famoso mundialmente?", "ricky martin"),
    ("¿Qué película ganó un Oscar con temática puertorriqueña?", "west side story"),
    ("¿Qué boxeador puertorriqueño es leyenda?", "felix trinidad"),
]

PUERTO_RICO_NORMAL = [
    ("¿En qué año llegó Juan Ponce de León a Puerto Rico?", "1508"),
    ("¿En qué año se fundó la primera capital?", "1508"),
    ("¿Quién fundó Caparra?", "juan ponce de leon"),
    ("¿En qué año se trasladó la capital a San Juan?", "1521"),
    ("¿En qué año se produjo la rebelión taína?", "1511"),
    ("¿Quién fue el líder taíno de la rebelión?", "agüeybana ii"),
    ("¿En qué año se creó el Obispado de San Juan?", "1511"),
    ("¿En qué año se construyó el Morro?", "1539"),
    ("¿En qué año se produjo el ataque de Francis Drake?", "1595"),
    ("¿En qué año se produjo el ataque de George Clifford?", "1598"),
    ("¿En qué año se produjo el ataque de los holandeses?", "1625"),
    ("¿En qué año se produjo la Real Cédula de Gracias?", "1815"),
    ("¿En qué año se produjo el Grito de Lares?", "1868"),
    ("¿Quién lideró el Grito de Lares?", "ramon emeterio betances"),
    ("¿En qué año se produjo la abolición de la esclavitud?", "1873"),
    ("¿En qué año se firmó la Carta Autonómica?", "1897"),
    ("¿En qué año se produjo la invasión estadounidense?", "1898"),
    ("¿En qué año se firmó el Tratado de París?", "1898"),
    ("¿En qué año se otorgó la ciudadanía estadounidense?", "1917"),
    ("¿En qué año se produjo la Masacre de Ponce?", "1937"),
]

PUERTO_RICO_DIFICIL = [
    ("¿En qué año llegó Colón a Puerto Rico?", "1493"),
    ("¿Quién fue el primer gobernador de Puerto Rico?", "juan ponce de leon"),
    ("¿En qué año se fundó Caparra?", "1508"),
    ("¿En qué año se trasladó la capital a San Juan?", "1521"),
    ("¿En qué año se produjo la rebelión de Agüeybaná II?", "1511"),
    ("¿En qué año se creó la Real Audiencia de San Juan?", "1832"),
    ("¿En qué año se produjo el ataque de Sir Francis Drake?", "1595"),
    ("¿En qué año se produjo el ataque de George Clifford?", "1598"),
    ("¿En qué año se produjo el ataque holandés?", "1625"),
    ("¿Quién lideró el ataque holandés a San Juan?", "boudewijn hendricksz"),
    ("¿En qué año se produjo el sitio de San Juan?", "1797"),
    ("¿Quién lideró la defensa de San Juan en 1797?", "ramon de castro"),
    ("¿En qué año se produjo la Real Cédula de Gracias?", "1815"),
    ("¿En qué año se produjo el Grito de Lares?", "1868"),
    ("¿Quién lideró el Grito de Lares?", "ramon emeterio betances"),
    ("¿En qué año se produjo la abolición de la esclavitud?", "1873"),
    ("¿En qué año se firmó la Carta Autonómica?", "1897"),
    ("¿En qué año se produjo la invasión estadounidense?", "1898"),
    ("¿En qué año se firmó el Tratado de París?", "1898"),
    ("¿En qué año se creó el Estado Libre Asociado?", "1952"),
]

# ============================================================
# NICARAGUA
# ============================================================
NICARAGUA_FACIL = [
    ("¿Cuál es la capital de Nicaragua?", "managua"),
    ("¿En qué año se independizó Nicaragua de España?", "1821"),
    ("¿Quién fue el prócer nicaragüense de la independencia?", "miguel larreynaga"),
    ("¿Cómo se llama la moneda oficial?", "cordoba"),
    ("¿Qué país limita al norte con Nicaragua?", "honduras"),
    ("¿Qué país limita al sur con Nicaragua?", "costa rica"),
    ("¿Cuál es el lago más grande de Nicaragua?", "cocibolca"),
    ("¿En qué año se fundó la República de Nicaragua?", "1838"),
    ("¿Quién fue el primer presidente de Nicaragua?", "fruto chamorro"),
    ("¿Qué cultura precolombina habitó Nicaragua?", "nicarao"),
    ("¿Cuál es el plato típico?", "gallo pinto"),
    ("¿Qué idioma se habla?", "espanol"),
    ("¿En qué año se abolió la esclavitud?", "1824"),
    ("¿Quién impulsó la educación en Nicaragua?", "jose santos zelaya"),
    ("¿En qué año se produjo la Revolución Sandinista?", "1979"),
    ("¿Quién fue el dictador entre 1936 y 1956?", "anastasio somoza garcia"),
    ("¿En qué año fue asesinado Somoza García?", "1956"),
    ("¿En qué año se produjo la guerra civil?", "1978"),
    ("¿En qué año se promulgó la Constitución actual?", "1987"),
    ("¿Qué poeta nicaragüense es famoso mundialmente?", "ruben dario"),
]

NICARAGUA_NORMAL = [
    ("¿En qué año llegó Gil González Dávila a Nicaragua?", "1522"),
    ("¿En qué año se fundó Granada?", "1524"),
    ("¿Quién fundó Granada?", "francisco hernandez de cordoba"),
    ("¿En qué año se fundó León?", "1524"),
    ("¿Quién fundó León?", "francisco hernandez de cordoba"),
    ("¿En qué año se creó la Provincia de Nicaragua?", "1527"),
    ("¿Quién fue el primer gobernador de Nicaragua?", "pedro arias davila"),
    ("¿En qué año se produjo la independencia de Nicaragua?", "1821"),
    ("¿Quién firmó el Acta de Independencia?", "miguel larreynaga"),
    ("¿En qué año se anexó Nicaragua a México?", "1822"),
    ("¿En qué año se separó Nicaragua de México?", "1823"),
    ("¿En qué año se creó el Estado de Nicaragua?", "1824"),
    ("¿Quién fue el primer jefe de estado de Nicaragua?", "manuel antonio de la cerda"),
    ("¿En qué año se separó Nicaragua de la Federación?", "1838"),
    ("¿En qué año se produjo la guerra nacional?", "1856"),
    ("¿Quién fue el filibustero estadounidense en Nicaragua?", "william walker"),
    ("¿En qué año fue fusilado William Walker?", "1860"),
    ("¿En qué año se produjo la Revolución Liberal?", "1893"),
    ("¿Quién lideró la Revolución Liberal de 1893?", "jose santos zelaya"),
    ("¿En qué año se produjo la intervención de EE.UU.?", "1912"),
]

NICARAGUA_DIFICIL = [
    ("¿En qué año llegó Gil González Dávila a Nicaragua?", "1522"),
    ("¿Quién fue el cacique nicaragüense que resistió?", "nicarao"),
    ("¿En qué año se fundó la ciudad de Granada?", "1524"),
    ("¿Quién fundó Granada?", "francisco hernandez de cordoba"),
    ("¿En qué año se fundó la ciudad de León?", "1524"),
    ("¿Quién fundó León?", "francisco hernandez de cordoba"),
    ("¿En qué año se creó la Provincia de Nicaragua?", "1527"),
    ("¿En qué año se trasladó la capital de Granada a León?", "1527"),
    ("¿En qué año se creó el Obispado de Nicaragua?", "1531"),
    ("¿En qué año se produjo el terremoto de León?", "1610"),
    ("¿En qué año se produjo el ataque de los piratas a Granada?", "1665"),
    ("¿Quién lideró el ataque pirata a Granada?", "francois l'ollonais"),
    ("¿En qué año se produjo la independencia de Nicaragua?", "1821"),
    ("¿Quién firmó el Acta de Independencia?", "miguel larreynaga"),
    ("¿En qué año se creó el Estado de Nicaragua?", "1824"),
    ("¿En qué año se separó Nicaragua de la Federación?", "1838"),
    ("¿Quién fue el primer presidente de Nicaragua?", "fruto chamorro"),
    ("¿En qué año se produjo la guerra nacional?", "1856"),
    ("¿En qué año fue fusilado William Walker?", "1860"),
    ("¿En qué año se creó el Banco Central de Nicaragua?", "1960"),
]

# ============================================================
# DICCIONARIO PRINCIPAL
# ============================================================
TRIVIA = {
    "mexico": {"facil": MEXICO_FACIL, "normal": MEXICO_NORMAL, "dificil": MEXICO_DIFICIL},
    "cuba": {"facil": CUBA_FACIL, "normal": CUBA_NORMAL, "dificil": CUBA_DIFICIL},
    "salvador": {"facil": EL_SALVADOR_FACIL, "normal": EL_SALVADOR_NORMAL, "dificil": EL_SALVADOR_DIFICIL},
    "ecuador": {"facil": ECUADOR_FACIL, "normal": ECUADOR_NORMAL, "dificil": ECUADOR_DIFICIL},
    "argentina": {"facil": ARGENTINA_FACIL, "normal": ARGENTINA_NORMAL, "dificil": ARGENTINA_DIFICIL},
    "colombia": {"facil": COLOMBIA_FACIL, "normal": COLOMBIA_NORMAL, "dificil": COLOMBIA_DIFICIL},
    "peru": {"facil": PERU_FACIL, "normal": PERU_NORMAL, "dificil": PERU_DIFICIL},
    "chile": {"facil": CHILE_FACIL, "normal": CHILE_NORMAL, "dificil": CHILE_DIFICIL},
    "venezuela": {"facil": VENEZUELA_FACIL, "normal": VENEZUELA_NORMAL, "dificil": VENEZUELA_DIFICIL},
    "guatemala": {"facil": GUATEMALA_FACIL, "normal": GUATEMALA_NORMAL, "dificil": GUATEMALA_DIFICIL},
    "honduras": {"facil": HONDURAS_FACIL, "normal": HONDURAS_NORMAL, "dificil": HONDURAS_DIFICIL},
    "costa_rica": {"facil": COSTA_RICA_FACIL, "normal": COSTA_RICA_NORMAL, "dificil": COSTA_RICA_DIFICIL},
    "panama": {"facil": PANAMA_FACIL, "normal": PANAMA_NORMAL, "dificil": PANAMA_DIFICIL},
    "bolivia": {"facil": BOLIVIA_FACIL, "normal": BOLIVIA_NORMAL, "dificil": BOLIVIA_DIFICIL},
    "paraguay": {"facil": PARAGUAY_FACIL, "normal": PARAGUAY_NORMAL, "dificil": PARAGUAY_DIFICIL},
    "uruguay": {"facil": URUGUAY_FACIL, "normal": URUGUAY_NORMAL, "dificil": URUGUAY_DIFICIL},
    "rep_dominicana": {"facil": REP_DOMINICANA_FACIL, "normal": REP_DOMINICANA_NORMAL, "dificil": REP_DOMINICANA_DIFICIL},
    "puerto_rico": {"facil": PUERTO_RICO_FACIL, "normal": PUERTO_RICO_NORMAL, "dificil": PUERTO_RICO_DIFICIL},
    "nicaragua": {"facil": NICARAGUA_FACIL, "normal": NICARAGUA_NORMAL, "dificil": NICARAGUA_DIFICIL},
}
