from telegram import Update
from telegram.ext import ContextTypes


async def actividades(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(
        "🎮 *MENÚ DE ACTIVIDADES*\n"
        "━━━━━━━━━━━━━━━━━━━\n\n"
        "🎰 *RULETA*\n"
        "Elige un color y prueba suerte.\n"
        "Uso: `/ruleta color`\n"
        "Apuesta: 20 tokens · Acierto: +50 tokens, +30 XP\n"
        "Cooldown: 5 min\n\n"
        "━━━━━━━━━━━━━━━━━━━\n\n"
        "🎲 *APUESTAS 1v1*\n"
        "Apuesta contra otro usuario.\n"
        "Uso: `/apostar cantidad`\n"
        "Mínimo 5 · Máximo 1000\n"
        "Premio: lo que apostó el rival\n"
        "Expira: 3 min sin rival\n"
        "Cooldown: 5 min\n\n"
        "━━━━━━━━━━━━━━━━━━━\n\n"
        "🧮 *MATEMÁTICAS*\n"
        "5 preguntas de mates.\n"
        "Uso: `/mates` (menú) o `/mates nivel`\n"
        "Premios: 10 / 30 / 50 / 80 / 120 tokens\n"
        "Respondes con: `.8`\n"
        "Cooldown: 7 min si pierdes, 5 si ganas\n\n"
        "━━━━━━━━━━━━━━━━━━━\n\n"
        "🎲 *DADOS*\n"
        "Tira 2 dados y apuesta.\n"
        "Uso: `/dados cantidad`\n"
        "Mínimo 10 · Máximo 500\n"
        "Suma 7 u 11 → x2 · Dobles → x3 · Otros → pierdes x2\n"
        "Cooldown: 5 min\n\n"
        "━━━━━━━━━━━━━━━━━━━\n\n"
        "🧠 *MEMORIA*\n"
        "Memoriza secuencias de emojis.\n"
        "Uso: `/memoria`\n"
        "Responde con `.` seguido de los emojis\n"
        "Cooldown: 7 min si pierdes, 10 si ganas\n\n"
        "━━━━━━━━━━━━━━━━━━━\n\n"
        "🧠 *TRIVIA DE HISTORIA*\n"
        "19 países + historia mundial (medieval y moderno).\n"
        "Uso: `/trivia <categoria> <dificultad>`\n"
        "Ejemplo: `/trivia mexico facil`\n"
        "Ejemplo: `/trivia medieval normal`\n"
        "Cooldown: 7 min si pierdes, 10 si ganas\n\n"
        "━━━━━━━━━━━━━━━━━━━\n\n"
        "🔤 *PALABRAS*\n"
        "Forma palabras con letras desordenadas.\n"
        "Uso: `/palabras`\n"
        "5 palabras · 40s cada una\n"
        "Premio: 50 tokens + 50 XP\n\n"
        "━━━━━━━━━━━━━━━━━━━\n\n"
        "🎵 *ADIVINA LA CANCIÓN (BETA)*\n"
        "Adivina funks por su letra.\n"
        "Uso: `/funks`\n"
        "Premio: 40 tokens + 45 XP\n"
        "⚠️ Versión beta.",
        parse_mode="Markdown"
    )
